DRAFT: scenario sequence diagrams
PWR-ACS-SE-24/SoftwareSystemDesign pull request #31
Opened 2024-12-17 13:43 UTC by jakubzehner

2024-12-17 15:18 UTC, jakubzehner commented
I wonder if we should add alt block for login sequence where login data is invalid and we do not create authorization token @tchojnacki

2024-12-17 18:49 UTC, mlodybercik requested changes
![1hf37d](https://github.com/user-attachments/assets/ce63401f-d0ed-4511-a207-51030528f666)

2024-12-17 18:49 UTC, mlodybercik commented on documentation/course/e2/images/sequence-diagram-scenario-ticket-inspection.drawio.svg
>display ticket information

It sounds funny, and arrow in the direction of JakPrzyjade implies that Passenger is displaying the code to our system. How about "get current ticket"? It's not bad, but it could be better I guess.

> handing out the fine

Shouldn't "handling" be infinitive? Every other verb is. How about: "Hand out the fine"?

2024-12-17 18:49 UTC, mlodybercik commented on documentation/course/e2/images/sequence-diagram-scenario-ticket-purchase.drawio.svg
Shouldn't self-call be partially overlapping the JakPrzyjade lifeline?

<sub>**nittest nit of all nits**: Payment Gateway is slimmer than JakPrzyjade</sub>

2024-12-17 19:59 UTC, mlodybercik approved these changes
![istockphoto-157030584-612x612](https://github.com/user-attachments/assets/b515bb3a-da3d-4d3e-8ce9-90c83668d3bf)

2024-12-18 15:29 UTC, tchojnacki commented
> I wonder if we should add alt block for login sequence where login data is invalid and we do not create authorization token @tchojnacki

Yes, as discussed, I'll add it.

2024-12-18 15:52 UTC, tchojnacki commented on documentation/course/e2/images/sequence-diagram-scenario-ticket-inspection.drawio.svg
It is probably invalid UML-wise, but it gets the point across, I like it.

Should the lines returning to the Passenger have some labels?

2024-12-18 15:52 UTC, tchojnacki commented on documentation/course/e2/images/sequence-diagram-scenario-ticket-purchase.drawio.svg
The return line from `charge wallet` seems unnecessary if we don't return anything. Note that activations without returns are valid UML:

![sequence-execution-spec-self](https://github.com/user-attachments/assets/8941457c-9bff-421f-bb5e-5428577c5d21)
![seq04](https://github.com/user-attachments/assets/fd52c4f5-5889-404c-a6ca-19192208b674)

2024-12-18 15:52 UTC, tchojnacki commented on documentation/course/e2/images/sequence-diagram-scenario-ticket-purchase.drawio.svg
This diverges from the prototype we had, where user had a payment option dropdown and had to explicitly select credit card to be charged. Is that on purpose?

2024-12-18 17:45 UTC, jakubzehner commented on documentation/course/e2/images/sequence-diagram-scenario-ticket-purchase.drawio.svg
done

2024-12-18 17:45 UTC, jakubzehner commented on documentation/course/e2/images/sequence-diagram-scenario-ticket-purchase.drawio.svg
resolved as discussed

2024-12-18 17:45 UTC, jakubzehner commented on documentation/course/e2/images/sequence-diagram-scenario-ticket-inspection.drawio.svg
resolved as discussed

2024-12-18 17:53 UTC, tchojnacki approved these changes

2024-12-18 17:54 UTC, merged